import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";

const xablau = Comic_Neue({
  weight: "300",
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={xablau.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
